### PR TITLE
readme: add lead dev havocr

### PR DESCRIPTION
**Pull request by nekomekoraiyuu**
Yanu april 1st joke (early)

### CODE REVIEW

**Comment by nozwock** [comment]
:unstretchedreaction:

**Comment by nekomekoraiyuu** [comment]
i will drop old bootstrap commit : unstretchedreaction:
(directed by lead yanu dev havocr)

**Comment by nekomekoraiyuu** [comment]
i think i should close this pr?
cause havocr mmjr 1 is over

**Comment by nozwock** [comment]
mmjr real

**Comment by havocr1** [comment]
Real

**Comment by nekomekoraiyuu** [comment]
rest in peace pro mmjr havocr PR 1

**Pull request closed without merging**
